"""init db

Revision ID: 78489f37cca7
Revises: 
Create Date: 2022-10-03 13:49:28.236436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78489f37cca7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'hidden', name='status'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('distinct', sa.Enum('район1', 'район2', 'район3', name='distinct'), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.Column('building_type', sa.Enum('новобудова', 'хрущовка', name='building_type'), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('square', sa.Integer(), nullable=True),
    sa.Column('num_of_rooms', sa.Integer(), nullable=True),
    sa.Column('layout', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('settlement_date', sa.DateTime(), nullable=True),
    sa.Column('price_uah', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advert')
    op.drop_table('user')
    # ### end Alembic commands ###
